name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - run: npm install
    - run: npm run lint
    - run: npm run build

    - name: Upload dist artifact
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-artifact@v1
      with:
        name: dist
        path: ./dist

  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v2
      
      - name: Download dist artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist/
      
      - name: Deploy
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: "sftp://${{ secrets.FTP_SERVER }}${{ secrets.FTP_PATH }}"
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          local-dir: "dist/"
          git-ftp-args: --insecure

      - name: Delete dist artifact
        uses: GeekyEggo/delete-artifact@v1.0.0
        with:
          name: dist
